name: feature_flow
description: Miniclient Feature Flow
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.2.0
  flutter: ^3.16.3

dependencies:
  flutter:
    sdk: flutter
  flow_builder: ^0.1.0
  get_it: ^7.6.4
  tide_di:
    path: ../tide_di

dev_dependencies:
  tide_analysis:
    path: ../tide_analysis

flutter:
  uses-material-design: true