name: tide_design_system
description: Design system
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.2.0
  flutter: ^3.16.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  tide_analysis:
    path: ../tide_analysis

flutter:
  uses-material-design: true